---
collections:
  - name: infra.aap_configuration
  - name: infra.aap_configuration_extended
  - name: infra.controller_configuration
  - name: infra.aap_utilities
  # Explicitly pin the Red Hat certified collections
  - name: ansible.controller
    version: ">=4.6.0"      # Use >=4.7.0 if you are on AAP 2.6+
  - name: ansible.platform
    version: ">=2.5.0"      # Use >=2.6.0 if you are on AAP 2.6+
  - name: ansible.eda
    version: ">=2.5.0"
  - name: ansible.hub
    version: ">=1.0.0"
  - name: amazon.aws
