---
controller_execution_environments_env:
  - name: "Johnlucca_Custom_EE_Development"
    description: "Development Execution Environment pointing to exact Git SHA"
    image: "ghcr.io/pbuehl-redhat/aap-configuration-as-code/cac-ee:{{ ee_image_tag | default('latest') }}"
    organization: "Johnlucca_Global_Admin"
    pull: "always"
